package com.c2pa.portal;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.util.*;
@Service public class CertificateRenewals {
 public record Claim(String id,Long workspace,String lease,String choiceId,Long choiceRevision,String providerVersion,PrivateCa.Configuration configuration,String identityId,String fingerprint,HardwareCertificateRequests.Subject subject,int renewBeforeHours){}
 private final CertificateRenewalPlanRepository plans;private final SigningOptionRepository options;private final PrivateCaSettingsRepository settings;private final PrivateCaVersionRepository versions;private final HardwareSigning hardware;private final HardwareCertificateRequests certificates;private final WorkspaceRepository workspaces;private final AuditService audit;private final ObjectMapper mapper;
 public CertificateRenewals(CertificateRenewalPlanRepository plans,SigningOptionRepository options,PrivateCaSettingsRepository settings,PrivateCaVersionRepository versions,HardwareSigning hardware,HardwareCertificateRequests certificates,WorkspaceRepository workspaces,AuditService audit,ObjectMapper mapper){this.plans=plans;this.options=options;this.settings=settings;this.versions=versions;this.hardware=hardware;this.certificates=certificates;this.workspaces=workspaces;this.audit=audit;this.mapper=mapper;}
 public CertificateRenewalPlan get(String id,Long workspace){return plans.findById(id).filter(p->p.workspaceId.equals(workspace)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private CertificateRenewalPlan locked(String id,Long workspace){workspaces.lockById(workspace).orElseThrow();return plans.lockById(id).filter(p->p.workspaceId.equals(workspace)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private SigningOption choice(String id,Long workspace,Long revision){if(id==null || revision==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Select a reviewed signing choice");var o=options.findById(id).filter(v->v.workspaceId.equals(workspace)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(!o.enabled || !Objects.equals(o.revision,revision) || !o.keyPath.startsWith("pkcs11:"))throw new ResponseStatusException(HttpStatus.CONFLICT,"Review an enabled hardware signing choice");return o;}
 private PrivateCa.Configuration provider(Long workspace,String id)throws Exception{if(id==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Select an active issuer");if(!settings.findById(workspace).map(s->Objects.equals(s.activeVersion,id)).orElse(false))throw new ResponseStatusException(HttpStatus.CONFLICT,"The pinned issuer is no longer active");var v=versions.findById(id).filter(p->p.workspaceId.equals(workspace) && p.testedAt!=null).orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"Activate a tested issuer first"));var c=mapper.readValue(v.configuration,PrivateCa.Configuration.class);if(!c.enabled())throw new ResponseStatusException(HttpStatus.CONFLICT,"The issuer is disabled");return c;}
 @Transactional public CertificateRenewalPlan create(Long workspace,String providerId,String choiceId,Long choiceRevision,HardwareCertificateRequests.Subject subject,int before)throws Exception{
  HardwareCertificateRequests.validateSubject(subject,true);workspaces.lockById(workspace).orElseThrow();var c=provider(workspace,providerId);var o=choice(choiceId,workspace,choiceRevision);if(before<1 || before>336 || before>=c.validityHours()-1 || subject==null || subject.commonName()==null || subject.commonName().isBlank() || subject.commonName().length()>200 || subject.organization()!=null && subject.organization().length()>200 || subject.country()!=null && !subject.country().isBlank() && !subject.country().matches("[A-Z]{2}"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Review a subject and renewal window shorter than the requested validity minus one hour");
  if(plans.existsByWorkspaceIdAndCurrentChoiceIdAndEnabledTrue(workspace,choiceId))throw new ResponseStatusException(HttpStatus.CONFLICT,"This choice already has an enabled renewal plan");var identity=hardware.get(o.keyPath.substring(7),workspace);var leaf=certificates.certificate(identity);leaf.checkValidity();if(!Objects.equals(identity.fingerprint,o.fingerprint))throw new ResponseStatusException(HttpStatus.CONFLICT,"Hardware certificate changed");
  var p=new CertificateRenewalPlan();p.id=UUID.randomUUID().toString();p.workspaceId=workspace;p.providerVersion=providerId;p.currentChoiceId=o.id;p.currentChoiceRevision=o.revision;p.subjectConfiguration=mapper.writeValueAsString(subject);p.renewBeforeHours=before;p.enabled=true;p.state="WAITING";p.createdAt=Instant.now();p.nextCheckAt=p.createdAt;plans.saveAndFlush(p);audit.record(workspace,"CERTIFICATE_RENEWAL_PLAN_CREATED",p.id);return p;
 }
 @Transactional public CertificateRenewalPlan enabled(Long workspace,String id,Long revision,boolean enabled,Long choiceRevision)throws Exception{var p=locked(id,workspace);if(!Objects.equals(p.revision,revision))throw new ResponseStatusException(HttpStatus.CONFLICT,"Renewal plan changed");if(enabled){provider(workspace,p.providerVersion);choice(p.currentChoiceId,workspace,choiceRevision);if(plans.existsByWorkspaceIdAndCurrentChoiceIdAndEnabledTrueAndIdNot(workspace,p.currentChoiceId,p.id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Another enabled plan already uses this choice");p.currentChoiceRevision=choiceRevision;p.state="WAITING";p.attempts=0;p.error=null;p.nextCheckAt=Instant.now();}else{p.state="PAUSED";}p.enabled=enabled;p.leaseToken=null;p.leaseUntil=null;plans.saveAndFlush(p);audit.record(workspace,enabled?"CERTIFICATE_RENEWAL_PLAN_RESUMED":"CERTIFICATE_RENEWAL_PLAN_PAUSED",p.id);return p;}
 private void block(CertificateRenewalPlan p,String error){p.enabled=false;p.state="BLOCKED";p.error=error;p.leaseToken=null;p.leaseUntil=null;plans.saveAndFlush(p);audit.record(p.workspaceId,"CERTIFICATE_RENEWAL_PLAN_BLOCKED",p.id);}
 @Transactional public Optional<Claim> claim(String id,boolean force,Long expectedRevision)throws Exception{
  var found=plans.findById(id);if(found.isEmpty())return Optional.empty();var p=locked(id,found.get().workspaceId);Instant now=Instant.now();if(force && !Objects.equals(p.revision,expectedRevision))throw new ResponseStatusException(HttpStatus.CONFLICT,"Renewal plan changed");if(!p.enabled || p.leaseUntil!=null && p.leaseUntil.isAfter(now) || !force && p.nextCheckAt.isAfter(now))return Optional.empty();
  PrivateCa.Configuration configuration;SigningOption o;HardwareIdentity identity;
  try{configuration=provider(p.workspaceId,p.providerVersion);o=choice(p.currentChoiceId,p.workspaceId,p.currentChoiceRevision);identity=hardware.get(o.keyPath.substring(7),p.workspaceId);if(!identity.fingerprint.equals(o.fingerprint))throw new IllegalStateException();var leaf=certificates.certificate(identity);leaf.checkValidity();if(!force && leaf.getNotAfter().toInstant().isAfter(now.plusSeconds(p.renewBeforeHours*3600L))){p.nextCheckAt=now.plusSeconds(300);plans.saveAndFlush(p);return Optional.empty();}}catch(Exception e){block(p,"Issuer or signing choice changed, or the source certificate is unavailable/expired. Review and resume the plan.");return Optional.empty();}
  if(p.attempts>=8){block(p,"Renewal attempt limit reached. Review and resume the plan.");return Optional.empty();}
  p.attempts++;p.state="RUNNING";p.error=null;p.leaseToken=UUID.randomUUID().toString();p.leaseUntil=now.plusSeconds(240);p.nextCheckAt=p.leaseUntil;plans.saveAndFlush(p);audit.record(p.workspaceId,"CERTIFICATE_RENEWAL_STARTED",p.id);
  return Optional.of(new Claim(p.id,p.workspaceId,p.leaseToken,o.id,o.revision,p.providerVersion,configuration,identity.id,identity.fingerprint,mapper.readValue(p.subjectConfiguration,HardwareCertificateRequests.Subject.class),p.renewBeforeHours));
 }
 @Transactional public boolean complete(Claim claim,String identityId)throws Exception{
  var p=locked(claim.id(),claim.workspace());if(!p.enabled || !Objects.equals(p.leaseToken,claim.lease()) || p.leaseUntil==null || p.leaseUntil.isBefore(Instant.now()))return false;
  SigningOption old;try{provider(p.workspaceId,p.providerVersion);old=choice(claim.choiceId(),p.workspaceId,claim.choiceRevision());if(!p.currentChoiceId.equals(old.id))throw new IllegalStateException();}catch(Exception e){block(p,"Issuer or reviewed choice changed during renewal; no replacement was published.");return false;}
  var identity=hardware.get(identityId,p.workspaceId);var leaf=certificates.certificate(identity);var source=certificates.certificate(hardware.get(old.keyPath.substring(7),p.workspaceId));if(identity.fingerprint.equals(old.fingerprint) || !java.security.MessageDigest.isEqual(source.getPublicKey().getEncoded(),leaf.getPublicKey().getEncoded()))throw new IllegalStateException("Replacement must use the existing key and a new certificate");if(identity.testedAt==null || leaf.getNotAfter().toInstant().isBefore(Instant.now().plusSeconds((p.renewBeforeHours+1)*3600L)))throw new IllegalStateException("Replacement certificate has insufficient validity");
  var renewed=new SigningOption();renewed.id=UUID.randomUUID().toString();renewed.workspaceId=p.workspaceId;renewed.label=old.label;renewed.settings=old.settings;renewed.profileRevision=old.profileRevision;renewed.fingerprint=identity.fingerprint;renewed.certificatePath=identity.certificatePath;renewed.keyPath="pkcs11:"+identity.id;renewed.development=false;renewed.enabled=true;renewed.createdAt=Instant.now();options.saveAndFlush(renewed);old.enabled=false;options.saveAndFlush(old);
  p.currentChoiceId=renewed.id;p.currentChoiceRevision=renewed.revision;p.lastIdentityId=identity.id;p.lastRenewedAt=Instant.now();p.attempts=0;p.state="WAITING";p.leaseToken=null;p.leaseUntil=null;p.error=null;p.nextCheckAt=Instant.now().plusSeconds(300);plans.saveAndFlush(p);audit.record(p.workspaceId,"CERTIFICATE_RENEWAL_CHOICE_PUBLISHED",p.id+":"+old.id+":"+renewed.id);return true;
 }
 @Transactional public void failed(Claim claim){var p=locked(claim.id(),claim.workspace());if(!Objects.equals(p.leaseToken,claim.lease()))return;p.leaseToken=null;p.leaseUntil=null;p.error="Renewal failed. Check CA/HSM configuration, template and certificate validity.";if(p.attempts>=8){p.state="FAILED";p.enabled=false;}else{p.state="RETRY_WAIT";p.nextCheckAt=Instant.now().plusSeconds(Math.min(3600,30L << p.attempts));}plans.saveAndFlush(p);audit.record(p.workspaceId,"CERTIFICATE_RENEWAL_"+p.state,p.id);}
}
