package com.c2pa.portal;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.*;
import org.springframework.web.server.ResponseStatusException;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import java.time.*;
import java.util.*;
@RestController public class OidcController {
 private final OidcService service;private final OidcSettingsRepository settings;private final OidcVersionRepository versions;private final OidcLinkRepository links;private final UserRepository users;private final WorkspaceRepository workspaces;private final WorkspaceService memberships;private final ObjectMapper mapper;private final AuditService audit;
 public OidcController(OidcService service,OidcSettingsRepository settings,OidcVersionRepository versions,OidcLinkRepository links,UserRepository users,WorkspaceRepository workspaces,WorkspaceService memberships,ObjectMapper mapper,AuditService audit){this.service=service;this.settings=settings;this.versions=versions;this.links=links;this.users=users;this.workspaces=workspaces;this.memberships=memberships;this.mapper=mapper;this.audit=audit;}
 public record Version(String id,OidcService.Configuration configuration,Instant createdAt,Instant testedAt){}
 public record State(Long revision,Version draft,Version active){}
 public record Draft(Long revision,OidcService.Configuration configuration){}
 public record Selection(Long revision,String versionId,boolean acknowledgeActivation){}
 public record Link(String username,String issuer,String subject){}
 public record Completion(String state,String code,String secondFactor){}
 private OidcSettings settings(){return settings.findById(1L).orElseGet(()->settings.saveAndFlush(new OidcSettings()));}
 private OidcSettings current(Long revision){workspaces.lockById(1L).orElseThrow();var s=settings();if(!Objects.equals(s.revision,revision))throw new ResponseStatusException(HttpStatus.CONFLICT,"Private login configuration changed");return s;}
 private OidcVersion version(String id){return versions.findById(Objects.requireNonNullElse(id,"")).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private Version view(OidcVersion v)throws Exception{return new Version(v.id,service.decode(v.configuration),v.createdAt,v.testedAt);}
 private State state(OidcSettings s)throws Exception{return new State(s.revision,s.draftVersion==null?null:view(version(s.draftVersion)),s.activeVersion==null?null:view(version(s.activeVersion)));}
 @GetMapping("/api/v1/admin/authentication/oidc") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public State get()throws Exception{return state(settings());}
 @PutMapping("/api/v1/admin/authentication/oidc/draft") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public State save(@RequestBody Draft draft)throws Exception{var s=current(draft.revision());var configuration=service.validate(draft.configuration());var v=new OidcVersion();v.id=UUID.randomUUID().toString();v.configuration=mapper.writeValueAsString(configuration);v.createdAt=Instant.now();versions.saveAndFlush(v);s.draftVersion=v.id;settings.saveAndFlush(s);audit.record(1L,"OIDC_DRAFT_SAVED",v.id);return state(s);}
 @PostMapping("/api/v1/admin/authentication/oidc/test") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public State test(@RequestBody Selection selection)throws Exception{var s=current(selection.revision());var v=version(selection.versionId());service.test(service.decode(v.configuration));v.testedAt=Instant.now();versions.saveAndFlush(v);audit.record(1L,"OIDC_DISCOVERY_TESTED",v.id);return state(s);}
 @PostMapping("/api/v1/admin/authentication/oidc/activate") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public State activate(@RequestBody Selection selection)throws Exception{if(!selection.acknowledgeActivation())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Acknowledge enabling this provider for linked accounts");var s=current(selection.revision());var v=version(selection.versionId());if(v.testedAt==null || v.testedAt.isBefore(Instant.now().minusSeconds(86400)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Test this provider version first");s.activeVersion=v.id;s.draftVersion=v.id;settings.saveAndFlush(s);audit.record(1L,"OIDC_PROVIDER_ACTIVATED",v.id);return state(s);}
 @GetMapping("/api/v1/admin/authentication/oidc/history") @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public List<Version> history(@RequestParam(defaultValue="0") int page)throws Exception{if(page<0 || page>10000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST);List<Version> result=new ArrayList<>();for(var v:versions.findAllByOrderByCreatedAtDesc(org.springframework.data.domain.PageRequest.of(page,50)))result.add(view(v));return result;}
 @GetMapping("/api/v1/admin/authentication/oidc/links") @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public List<OidcLink> links(@RequestParam(defaultValue="0") int page){if(page<0 || page>10000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST);return links.findAll(org.springframework.data.domain.PageRequest.of(page,50)).getContent();}
 @PostMapping("/api/v1/admin/authentication/oidc/links") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public OidcLink link(@RequestBody Link request){if(request.issuer()==null || request.issuer().isBlank() || request.issuer().length()>800 || !request.issuer().chars().allMatch(ch->ch>32 && ch<127) || request.subject()==null || request.subject().isBlank() || request.subject().length()>255)throw new ResponseStatusException(HttpStatus.BAD_REQUEST);workspaces.lockById(1L).orElseThrow();if(links.findByIssuerAndSubject(request.issuer(),request.subject()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Subject is already linked");var account=users.findByUsername(Objects.requireNonNullElse(request.username(),"")).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));var link=new OidcLink();link.userId=account.id;link.issuer=request.issuer();link.subject=request.subject();link=links.saveAndFlush(link);audit.record(1L,"OIDC_ACCOUNT_LINKED",link.id.toString());return link;}
 @DeleteMapping("/api/v1/admin/authentication/oidc/links/{id}") @Transactional @io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken") public Map<String,Boolean> unlink(@PathVariable Long id){var link=links.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));links.delete(link);audit.record(1L,"OIDC_ACCOUNT_UNLINKED",id.toString());return Map.of("unlinked",true);}
 @GetMapping("/api/v1/auth/oidc/status") public Map<String,Boolean> status(){return Map.of("enabled",service.enabled());}
 @PostMapping("/api/v1/auth/oidc/start") public ResponseEntity<Map<String,String>> start()throws Exception{var started=service.start();String cookie=ResponseCookie.from("C2PA_OIDC_BROWSER",started.browserProof()).httpOnly(true).secure(started.secureCookie()).sameSite("Lax").path("/api/v1/auth/oidc").maxAge(Duration.ofMinutes(10)).build().toString();return ResponseEntity.ok().header(HttpHeaders.SET_COOKIE,cookie).header(HttpHeaders.CACHE_CONTROL,"no-store").body(Map.of("authorizationUrl",started.authorizationUrl()));}
 @PostMapping("/api/v1/auth/oidc/complete") public ResponseEntity<AccountService.Login> complete(@RequestBody Completion completion,@CookieValue(name="C2PA_OIDC_BROWSER",required=false) String browser,HttpServletRequest request)throws Exception{var login=service.complete(completion.state(),browser,completion.code(),completion.secondFactor());try{request.setAttribute("portal.workspaceId",memberships.select(users.findById(login.user().id()).orElseThrow(),null).id());}catch(ResponseStatusException e){request.setAttribute("portal.workspaceId",0L);}request.setAttribute("portal.actor",login.user().username());audit.record("OIDC_USER_LOGIN",login.user().id().toString());return ResponseEntity.ok().header(HttpHeaders.CACHE_CONTROL,"no-store").header(HttpHeaders.SET_COOKIE,ResponseCookie.from("C2PA_OIDC_BROWSER","").httpOnly(true).sameSite("Lax").path("/api/v1/auth/oidc").maxAge(0).build().toString()).body(login);}
}
