package com.c2pa.portal;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.data.domain.PageRequest;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import java.time.Instant;
import java.util.*;
import java.io.*;
import java.nio.file.*;
@RestController @RequestMapping("/api/v1/admin/remote-workers")
@io.swagger.v3.oas.annotations.security.SecurityRequirement(name="adminToken")
public class RemoteWorkersController {
 public record Worker(String id,Long revision,String label,boolean enabled,Instant expiresAt,Instant lastSeenAt,Instant testedAt,String probeJobId,boolean namespaceAvailable){}
 public record State(Long revision,boolean remoteQueuedSigning,boolean agentEnabled,RemoteWorkerAgent.Configuration agentConfiguration,Instant agentTestedAt,RemoteWorkerAgent.Status agentStatus){}
 public record Create(String label,int validityDays){}
 public record Selection(Long revision,boolean enabled,boolean acknowledgeTrustedExecutor){}
 public record Routing(Long revision,boolean enabled,boolean acknowledgeHardwareOnly){}
 public record AgentDraft(Long revision,RemoteWorkerAgent.Configuration configuration){}
 public record Probe(Long revision,String signingChoiceId,Long signingChoiceRevision,boolean acknowledgePublicProbe){}
 private final RemoteWorkerLeases leases;private final RemoteWorkerRepository workers;private final RemoteWorkerSettingsRepository settings;private final WorkspaceRepository workspaces;private final RemoteWorkerSecurity security;private final RemoteWorkerAgent agent;private final JobService jobs;private final SigningChoices choices;private final ObjectMapper mapper;private final AuditService audit;
 public RemoteWorkersController(RemoteWorkerRepository workers,RemoteWorkerSettingsRepository settings,WorkspaceRepository workspaces,RemoteWorkerSecurity security,RemoteWorkerAgent agent,JobService jobs,SigningChoices choices,ObjectMapper mapper,AuditService audit,RemoteWorkerLeases leases){this.leases=leases;this.workers=workers;this.settings=settings;this.workspaces=workspaces;this.security=security;this.agent=agent;this.jobs=jobs;this.choices=choices;this.mapper=mapper;this.audit=audit;}
 private Worker view(RemoteWorker w){return new Worker(w.id,w.revision,w.label,w.enabled,w.expiresAt,w.lastSeenAt,w.testedAt,w.probeJobId,w.namespaceAvailable);}
 private RemoteWorker worker(String id,Long revision){var w=workers.lockById(id).filter(row->row.workspaceId.equals(WorkspaceContext.id())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(!Objects.equals(w.revision,revision))throw new ResponseStatusException(HttpStatus.CONFLICT,"Worker changed; refresh before reviewing");return w;}
 private RemoteWorkerSettings settings(){return settings.findById(WorkspaceContext.id()).orElseGet(()->{workspaces.lockById(WorkspaceContext.id()).orElseThrow();return settings.findById(WorkspaceContext.id()).orElseGet(()->{var s=new RemoteWorkerSettings();s.id=WorkspaceContext.id();return settings.saveAndFlush(s);});});}
 private RemoteWorkerSettings current(Long revision){workspaces.lockById(WorkspaceContext.id()).orElseThrow();var s=settings();if(!Objects.equals(s.revision,revision))throw new ResponseStatusException(HttpStatus.CONFLICT,"Remote settings changed");return s;}
 private State state(RemoteWorkerSettings s)throws Exception{return new State(s.revision,s.remoteQueuedSigning,s.agentEnabled,s.agentConfiguration==null?null:agent.decode(s.agentConfiguration),s.agentTestedAt,agent.status(s.id));}
 @GetMapping public List<Worker> list(@RequestParam(defaultValue="0")int page){if(page<0 || page>10000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST);return workers.findByWorkspaceIdOrderByCreatedAtDesc(WorkspaceContext.id(),PageRequest.of(page,50)).stream().map(this::view).toList();}
 @PostMapping @Transactional public Map<String,Object> create(@RequestBody Create request){if(request.label()==null || request.label().isBlank() || request.label().length()>120 || request.validityDays()<1 || request.validityDays()>90)throw new ResponseStatusException(HttpStatus.BAD_REQUEST);workspaces.lockById(WorkspaceContext.id()).orElseThrow();if(workers.countByWorkspaceId(WorkspaceContext.id())>=100)throw new ResponseStatusException(HttpStatus.CONFLICT,"Workspace worker limit reached");var w=new RemoteWorker();w.id=UUID.randomUUID().toString();w.workspaceId=WorkspaceContext.id();w.label=request.label().trim();w.createdAt=Instant.now();String token=security.issue(w,request.validityDays());workers.saveAndFlush(w);audit.record("REMOTE_WORKER_REGISTERED",w.id);return Map.of("worker",view(w),"pairingToken",token);}
 @PostMapping("/{id}/rotate") @Transactional public Map<String,Object> rotate(@PathVariable String id,@RequestBody Selection request){var w=worker(id,request.revision());leases.withdrawProbe(w);String token=security.issue(w,30);w.enabled=false;w.testedAt=null;w.probeJobId=null;workers.saveAndFlush(w);audit.record("REMOTE_WORKER_CREDENTIAL_ROTATED",w.id);return Map.of("worker",view(w),"pairingToken",token);}
 @PutMapping("/{id}") @Transactional public Worker enable(@PathVariable String id,@RequestBody Selection request){var w=worker(id,request.revision());if(request.enabled() && (!request.acknowledgeTrustedExecutor() || w.testedAt==null || w.testedAt.isBefore(Instant.now().minusSeconds(86400)) || !w.expiresAt.isAfter(Instant.now()) || w.lastSeenAt==null || w.lastSeenAt.isBefore(Instant.now().minusSeconds(120))))throw new ResponseStatusException(HttpStatus.CONFLICT,"Acknowledge a trusted executor and complete a recent remote signing probe first");w.enabled=request.enabled();if(!w.enabled){leases.withdrawProbe(w);w.probeJobId=null;w.testedAt=null;}workers.saveAndFlush(w);audit.record(w.enabled?"REMOTE_WORKER_ACTIVATED":"REMOTE_WORKER_WITHDRAWN",w.id);return view(w);}
 @PostMapping("/{id}/revoke") @Transactional public Worker revoke(@PathVariable String id,@RequestBody Selection request){var w=worker(id,request.revision());leases.withdrawProbe(w);w.enabled=false;w.testedAt=null;w.probeJobId=null;w.expiresAt=Instant.now();workers.saveAndFlush(w);audit.record("REMOTE_WORKER_CREDENTIAL_REVOKED",w.id);return view(w);}
 @PostMapping("/{id}/probe") @Transactional(rollbackFor=Exception.class) public Map<String,Object> probe(@PathVariable String id,@RequestBody Probe request,HttpServletRequest http)throws Exception{
  var w=worker(id,request.revision());if(!request.acknowledgePublicProbe() || w.enabled || !w.expiresAt.isAfter(Instant.now()) || w.lastSeenAt==null || w.lastSeenAt.isBefore(Instant.now().minusSeconds(120)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Pair a paused worker and acknowledge a generated public probe");
  leases.prepareProbe(w);
  var selected=choices.select(request.signingChoiceId(),request.signingChoiceRevision());if(!selected.material().key().toString().startsWith("pkcs11:"))throw new ResponseStatusException(HttpStatus.CONFLICT,"Select a hardware identity");
  var image=new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB);var buffer=new ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",buffer);byte[] png=buffer.toByteArray();
  var file=new org.springframework.web.multipart.MultipartFile(){public String getName(){return "file";}public String getOriginalFilename(){return "remote-probe.png";}public String getContentType(){return "image/png";}public boolean isEmpty(){return false;}public long getSize(){return png.length;}public byte[] getBytes(){return png.clone();}public InputStream getInputStream(){return new ByteArrayInputStream(png);}public void transferTo(java.io.File destination)throws IOException{Files.write(destination.toPath(),png);}};
  var job=jobs.submit(file,"Remote worker readiness","Remote worker public probe","none",(String)http.getAttribute("portal.actor"),UUID.randomUUID().toString(),selected.profileRevision(),selected.material().fingerprint(),selected.optionId(),selected.optionRevision(),w.id);w.probeJobId=job.id;w.testedAt=null;workers.saveAndFlush(w);audit.record("REMOTE_WORKER_PROBE_SUBMITTED",w.id+":"+job.id);return Map.of("worker",view(w),"jobId",job.id);
 }
 @GetMapping("/settings") @Transactional public State get()throws Exception{return state(settings());}
 @PutMapping("/routing") @Transactional public State routing(@RequestBody Routing request)throws Exception{var s=current(request.revision());if(request.enabled() && (!request.acknowledgeHardwareOnly() || !workers.existsByWorkspaceIdAndEnabledTrueAndExpiresAtAfter(s.id,Instant.now())))throw new ResponseStatusException(HttpStatus.CONFLICT,"Activate a tested worker and acknowledge hardware-only queued signing");s.remoteQueuedSigning=request.enabled();settings.saveAndFlush(s);audit.record("REMOTE_SIGNING_ROUTING_CHANGED",String.valueOf(s.remoteQueuedSigning));return state(s);}
 @PutMapping("/agent") @Transactional public State draft(@RequestBody AgentDraft request)throws Exception{var s=current(request.revision());agent.validate(s.id,request.configuration());s.agentConfiguration=mapper.writeValueAsString(request.configuration());s.agentEnabled=false;s.agentTestedAt=null;settings.saveAndFlush(s);audit.record("REMOTE_AGENT_CONFIGURATION_SAVED",String.valueOf(s.revision));return state(s);}
 @PostMapping("/agent/test") @Transactional public State test(@RequestBody Selection request)throws Exception{var s=current(request.revision());if(s.agentConfiguration==null)throw new ResponseStatusException(HttpStatus.CONFLICT);try{agent.test(s.id,agent.decode(s.agentConfiguration));}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"Agent connection failed; check pairing credential, TLS and worker runtime");}s.agentTestedAt=Instant.now();settings.saveAndFlush(s);audit.record("REMOTE_AGENT_CONNECTION_TESTED",String.valueOf(s.revision));return state(s);}
 @PostMapping("/agent/activate") @Transactional public State activate(@RequestBody Selection request)throws Exception{var s=current(request.revision());if(request.enabled() && (!request.acknowledgeTrustedExecutor() || s.agentTestedAt==null || s.agentTestedAt.isBefore(Instant.now().minusSeconds(86400))))throw new ResponseStatusException(HttpStatus.CONFLICT,"Test the connection and acknowledge a trusted executor first");s.agentEnabled=request.enabled();settings.saveAndFlush(s);audit.record(s.agentEnabled?"REMOTE_AGENT_ACTIVATED":"REMOTE_AGENT_PAUSED",String.valueOf(s.revision));return state(s);}
}
