server {
    listen 5173;
    server_name _;
    client_max_body_size 101m;
    root /usr/share/nginx/html;
    location /api/ {
        proxy_pass http://api:8080;
        proxy_read_timeout 60s;
        proxy_set_header Host $host;
    }
    location /swagger-ui/ { proxy_pass http://api:8080; }
    location /v3/ { proxy_pass http://api:8080; }
    location / { try_files $uri $uri/ /index.html; }
}
