package com.c2pa.portal;
import org.junit.jupiter.api.Test;
import org.flywaydb.core.Flyway;
import java.sql.DriverManager;
import static org.junit.jupiter.api.Assertions.*;
class LegacyMigrationsTest {
 @Test void upgradeKeepsExistingProfilesAuditAndJobSnapshots()throws Exception {
  String url="jdbc:h2:mem:pre-flyway-fixture;DB_CLOSE_DELAY=-1";
  try(var connection=DriverManager.getConnection(url,"sa","");var sql=connection.createStatement()){
   sql.execute("create table configuration_record(id bigint primary key,revision bigint,active varchar(16000),draft varchar(16000))");sql.execute("insert into configuration_record values(1,4,'active-profile-snapshot','unsaved-draft')");
   sql.execute("create table audit_event(id bigint generated by default as identity primary key,created_at timestamp(6) with time zone,actor varchar(255),action varchar(255),reference varchar(255))");sql.execute("insert into audit_event(actor,action,reference) values('legacy-user','SIGNED','legacy-reference')");
   sql.execute("create table asset_storage(id bigint primary key,revision bigint,retention_days integer not null)");sql.execute("insert into asset_storage values(1,2,90)");
   sql.execute("create table signing_job(id varchar(255) primary key,revision bigint,request_key varchar(255) unique,request_digest varchar(255),owner varchar(255),state varchar(255),format varchar(255),title varchar(255),fingerprint varchar(255),certificate_path varchar(255),key_path varchar(255),error varchar(255),created_at timestamp(6) with time zone,completed_at timestamp(6) with time zone,attempts integer not null)");sql.execute("insert into signing_job(id,owner,state,format,certificate_path,key_path,attempts) values('legacy-job','legacy-user','COMPLETED','image/png','/preserved/cert.pem','/preserved/key.pem',1)");
  }
  var flyway=Flyway.configure().dataSource(url,"sa","").baselineOnMigrate(true).baselineVersion("0").load();assertEquals(5,flyway.migrate().migrationsExecuted);assertEquals(0,flyway.migrate().migrationsExecuted);assertTrue(flyway.validateWithResult().validationSuccessful);
  try(var connection=DriverManager.getConnection(url,"sa","");var sql=connection.createStatement()){
   try(var result=sql.executeQuery("select active,draft,revision from configuration_record where id=1")){assertTrue(result.next());assertEquals("active-profile-snapshot",result.getString(1));assertEquals("unsaved-draft",result.getString(2));assertEquals(4,result.getLong(3));}
   try(var result=sql.executeQuery("select workspace_id,actor,reference,chain_index,legacy_imported from audit_event")){assertTrue(result.next());assertEquals(1,result.getLong(1));assertEquals("legacy-user",result.getString(2));assertEquals("legacy-reference",result.getString(3));assertNull(result.getObject(4));assertFalse(result.getBoolean(5));}
   try(var result=sql.executeQuery("select workspace_id,max_attempts,worker_timeout_seconds,result_attempt,key_path from signing_job")){assertTrue(result.next());assertEquals(1,result.getLong(1));assertEquals(10,result.getInt(2));assertEquals(45,result.getInt(3));assertNull(result.getString(4));assertEquals("/preserved/key.pem",result.getString(5));}
   try(var result=sql.executeQuery("select retention_days from asset_storage")){assertTrue(result.next());assertEquals(90,result.getInt(1));}
  }
 }
}
