package com.c2pa.portal;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.security.*;
import java.time.Instant;
import java.util.*;
import java.math.BigInteger;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x509.*;
import org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder;
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder;
class OfficialPublicTrustTest {
 @org.junit.jupiter.api.io.TempDir java.nio.file.Path folder;
 private final ObjectMapper mapper=new ObjectMapper();
 private OfficialPublicTrust service(){return new OfficialPublicTrust(mapper,mock(PublicTrustSettingsRepository.class),mock(PublicTrustVersionRepository.class),mock(WorkerExecution.class));}
 private String certificate(boolean ca)throws Exception{var g=KeyPairGenerator.getInstance("EC");g.initialize(new java.security.spec.ECGenParameterSpec("secp256r1"));var key=g.generateKeyPair();var name=new X500Name("CN=Disposable Test CA");var b=new JcaX509v3CertificateBuilder(name,BigInteger.ONE,Date.from(Instant.now().minusSeconds(3600)),Date.from(Instant.now().plusSeconds(86400)),name,key.getPublic());b.addExtension(org.bouncycastle.asn1.x509.Extension.basicConstraints,true,new BasicConstraints(ca));b.addExtension(org.bouncycastle.asn1.x509.Extension.keyUsage,true,new KeyUsage(ca?KeyUsage.keyCertSign|KeyUsage.cRLSign:KeyUsage.digitalSignature));return Base64.getEncoder().encodeToString(b.build(new JcaContentSignerBuilder("SHA256withECDSA").build(key.getPrivate())).getEncoded());}
 private String list(String certificate,boolean tsa,long sequence,Instant issue,Instant next,Instant start,String status)throws Exception{
  var information=Map.of("LoTEVersionIdentifier",1,"LoTESequenceNumber",sequence,"SchemeName",List.of(Map.of("value",tsa?"C2PA TSA Trust List":"C2PA Trust List")),"ListIssueDateTime",issue.toString(),"NextUpdate",next.toString());
  var service=Map.of("ServiceStatus",status,"StatusStartingTime",start.toString(),"ServiceDigitalIdentity",Map.of("X509Certificates",List.of(Map.of("val",certificate))));
  return mapper.writeValueAsString(Map.of("LoTE",Map.of("ListAndSchemeInformation",information,"TrustedEntitiesList",List.of(Map.of("TrustedEntityServices",List.of(Map.of("ServiceInformation",service)))))));
 }

 @Test void parsesStrongCaAndPreservesServiceStartTime()throws Exception{var now=Instant.now();var json=list(certificate(true),false,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");var parsed=service().parse(json,false);assertEquals(1,parsed.anchors().size());assertEquals(now.minusSeconds(3600),parsed.anchors().getFirst().trustedFrom());assertEquals(64,parsed.sha256().length());assertThrows(Exception.class,()->service().parse(json,true));assertThrows(Exception.class,()->service().parse(json.replace("LoTEVersionIdentifier\":1","LoTEVersionIdentifier\":99"),false));}
 @Test void nonCaWithdrawnFutureIssueAndInvalidPeriodsAreRejected()throws Exception{var now=Instant.now();var ca=certificate(true);for(var json:List.of(list(certificate(false),false,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted"),list(ca,false,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/withdrawn"),list(ca,false,1,now.plusSeconds(3600),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted"),list(ca,false,1,now.minusSeconds(60),now.minusSeconds(120),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted")))assertThrows(Exception.class,()->service().parse(json,false));}
 @Test void cacheExpiryAndMonotonicSourceVersions()throws Exception{var now=Instant.now();var ca=certificate(true);var original=new PublicTrustVersion();original.configuration=mapper.writeValueAsString(new OfficialPublicTrust.Configuration(true,24,"","",false));original.fetchedAt=now;original.signerList=list(ca,false,2,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");original.tsaList=list(ca,true,2,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");assertTrue(service().summary(original).current());original.fetchedAt=now.minusSeconds(90000);assertFalse(service().summary(original).current());var older=new PublicTrustVersion();older.configuration=original.configuration;older.signerList=list(ca,false,1,now.minusSeconds(120),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");older.tsaList=original.tsaList;assertThrows(Exception.class,()->service().preventRollback(original,older));assertDoesNotThrow(()->service().preventRollback(original,original));}
 @Test void sourceCannotBeReplacedAndProxyRequiresExplicitTrust()throws Exception{assertTrue(OfficialPublicTrust.SIGNER_SOURCE.startsWith("https://raw.githubusercontent.com/c2pa-org/conformance-public/"));assertFalse(Arrays.stream(OfficialPublicTrust.Configuration.class.getRecordComponents()).anyMatch(c->c.getName().equals("source")));assertThrows(Exception.class,()->service().validate(new OfficialPublicTrust.Configuration(true,24,"http://127.0.0.1:3128","",false)));assertThrows(Exception.class,()->service().validate(new OfficialPublicTrust.Configuration(true,200,"","",false)));}
 private String pem(Object value)throws Exception{var out=new java.io.StringWriter();try(var w=new org.bouncycastle.openssl.jcajce.JcaPEMWriter(out)){w.writeObject(value);}return out.toString();}
 @Test void actualSdkAcceptsEligibleFixtureAnchorAndRejectsMissingConformanceEku()throws Exception{
  // Synthetic trust-list records exercise the validator, never the authenticated production downloader.
  var generator=KeyPairGenerator.getInstance("EC");generator.initialize(new java.security.spec.ECGenParameterSpec("secp256r1"));var issuer=generator.generateKeyPair();var leafKey=generator.generateKeyPair();var name=new X500Name("CN=Fixture Root");var now=Instant.now();
  var rootBuilder=new JcaX509v3CertificateBuilder(name,BigInteger.ONE,Date.from(now.minusSeconds(3600)),Date.from(now.plusSeconds(86400)),name,issuer.getPublic());rootBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.basicConstraints,true,new BasicConstraints(true));rootBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.keyUsage,true,new KeyUsage(KeyUsage.keyCertSign|KeyUsage.cRLSign));
  var identifiers=new org.bouncycastle.cert.jcajce.JcaX509ExtensionUtils();rootBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.subjectKeyIdentifier,false,identifiers.createSubjectKeyIdentifier(issuer.getPublic()));rootBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.authorityKeyIdentifier,false,identifiers.createAuthorityKeyIdentifier(issuer.getPublic()));
  var root=new org.bouncycastle.cert.jcajce.JcaX509CertificateConverter().getCertificate(rootBuilder.build(new JcaContentSignerBuilder("SHA256withECDSA").build(issuer.getPrivate())));
  java.nio.file.Path worker=java.nio.file.Path.of("../c2pa-worker/target/debug/c2pa-worker").toAbsolutePath();assertTrue(java.nio.file.Files.isExecutable(worker),"Build the pinned Rust worker before Java tests");
  var runtime=new WorkerExecution(mock(HardwareSigning.class),mock(TrustPolicy.class),mock(PrivateTimestamps.class),new WorkerSandbox(mock(ProcessingRepository.class)),mock(CertificateRevocations.class));
  var trust=new OfficialPublicTrust(mapper,mock(PublicTrustSettingsRepository.class),mock(PublicTrustVersionRepository.class),runtime);var version=new PublicTrustVersion();version.id="synthetic-validator-fixture";version.workspaceId=1L;version.fetchedAt=now;version.configuration=mapper.writeValueAsString(new OfficialPublicTrust.Configuration(true,24,"","",false));
  var encoded=Base64.getEncoder().encodeToString(root.getEncoded());version.signerList=list(encoded,false,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");version.tsaList=list(encoded,true,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");
  var input=folder.resolve("original.png");javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB),"png",input.toFile());var definition=folder.resolve("manifest.json");java.nio.file.Files.writeString(definition,"{\"claim_generator_info\":[{\"name\":\"Synthetic validation fixture\",\"version\":\"1\"}],\"title\":\"Fixture\",\"format\":\"image/png\",\"assertions\":[{\"label\":\"com.c2pa.portal.declarations\",\"data\":{\"source\":\"synthetic-test-only\"}}]}");
  var key=folder.resolve("key.pem");java.nio.file.Files.createFile(key,java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rw-------")));java.nio.file.Files.writeString(key,pem(new org.bouncycastle.util.io.pem.PemObject("PRIVATE KEY",leafKey.getPrivate().getEncoded())));
  for(boolean conformant:new boolean[]{true,false}){
   var leafBuilder=new JcaX509v3CertificateBuilder(name,conformant?BigInteger.TWO:BigInteger.TEN,Date.from(now.minusSeconds(60)),Date.from(now.plusSeconds(3600)),new X500Name("CN=Fixture Signer"),leafKey.getPublic());leafBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.basicConstraints,true,new BasicConstraints(false));leafBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.keyUsage,true,new KeyUsage(KeyUsage.digitalSignature));
   leafBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.authorityKeyIdentifier,false,identifiers.createAuthorityKeyIdentifier(issuer.getPublic()));leafBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.subjectKeyIdentifier,false,identifiers.createSubjectKeyIdentifier(leafKey.getPublic()));
   var purpose=conformant?KeyPurposeId.getInstance(new org.bouncycastle.asn1.ASN1ObjectIdentifier("1.3.6.1.4.1.62558.2.1")):KeyPurposeId.id_kp_emailProtection;leafBuilder.addExtension(org.bouncycastle.asn1.x509.Extension.extendedKeyUsage,false,new ExtendedKeyUsage(purpose));var leaf=new org.bouncycastle.cert.jcajce.JcaX509CertificateConverter().getCertificate(leafBuilder.build(new JcaContentSignerBuilder("SHA256withECDSA").build(issuer.getPrivate())));
   assertEquals(conformant,leaf.getExtendedKeyUsage().contains("1.3.6.1.4.1.62558.2.1"));
   var chain=folder.resolve("chain.pem");java.nio.file.Files.writeString(chain,pem(leaf)+pem(root));var output=folder.resolve(conformant?"conformant.png":"legacy.png");var exit=runtime.sign(1L,worker,input,output,definition,chain,key.toString(),folder.resolve("sign-report.json"),folder.resolve("sign-error.log"),30);assertEquals(0,exit,()->{try{return "conformant="+conformant+" EKU="+leaf.getExtendedKeyUsage()+" "+java.nio.file.Files.readString(folder.resolve("sign-error.log"));}catch(Exception e){return "Native fixture failed";}});
   var result=trust.evaluate(version,output,folder);assertEquals(conformant,result.path("publicTrustVerified").asBoolean(),()->{try{return "conformant="+conformant+" "+result+" statuses="+mapper.readTree(folder.resolve("official-report.json").toFile()).path("validation_results");}catch(Exception e){return "Public trust fixture failed";}});assertFalse(result.path("onlineRevocationChecked").asBoolean());
   if(conformant){
    var selections=mock(PublicTrustSettingsRepository.class);var records=mock(PublicTrustVersionRepository.class);var selected=new PublicTrustSettings();selected.id=1L;selected.activeVersion=version.id;when(selections.findById(1L)).thenReturn(Optional.of(selected));when(records.findById(version.id)).thenReturn(Optional.of(version));var activeTrust=new OfficialPublicTrust(mapper,selections,records,runtime);
    var currentList=version.signerList;version.signerList=list(certificate(true),false,1,now.minusSeconds(60),now.plusSeconds(86400),now.minusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");assertFalse(activeTrust.evaluateActive(1L,output,folder).path("publicTrustVerified").asBoolean(),"TSA-only roots must not establish signer trust");version.signerList=currentList;version.signerList=list(encoded,false,1,now.minusSeconds(60),now.plusSeconds(86400),now.plusSeconds(3600),"http://c2pa.org/conformance/trust-list/trusted");assertFalse(activeTrust.evaluateActive(1L,output,folder).path("publicTrustVerified").asBoolean());version.signerList=currentList;
    version.fetchedAt=now.minusSeconds(90000);var stale=activeTrust.evaluateActive(1L,output,folder);assertFalse(stale.path("publicTrustVerified").asBoolean());assertEquals("STALE",stale.path("status").asText());version.fetchedAt=now;
   }
  }
 }
}
