create table oidc_settings(id bigint primary key,revision bigint,draft_version varchar(255),active_version varchar(255));
create table oidc_version(id varchar(255) primary key,configuration varchar(16000),created_at timestamp(6) with time zone,tested_at timestamp(6) with time zone);
create table oidc_link(id bigint generated by default as identity primary key,user_id bigint,issuer varchar(2000) not null,subject varchar(255) not null,unique(issuer,subject));
create table oidc_transaction(id varchar(255) primary key,browser_hash varchar(255),version_id varchar(255),proof_credential varchar(255),expires_at timestamp(6) with time zone,consumed boolean not null);
