import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
type Settings = {
  organizationName: string;
  profileName: string;
  formats: string[];
  maxUploadMb: number;
  requireAiDisclosure: boolean;
};
type State = {
  draft: Settings;
  active: Settings | null;
  revision: number;
  signingAvailable: boolean;
};
function App() {
  const [token, setToken] = useState("");
  const [state, setState] = useState<State | null>(null);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [report, setReport] = useState<unknown>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [tested, setTested] = useState(false);
  const [saved, setSaved] = useState(true);
  async function request(path: string, method = "GET", body?: unknown) {
    const response = await fetch("/api/v1/admin/configuration" + path, {
      method,
      headers: { "Content-Type": "application/json", "X-Admin-Token": token },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok)
      throw new Error(
        response.status === 401
          ? "Invalid administrator token."
          : response.status === 409
            ? "Settings changed. Reconnect to load the current revision."
            : `Request failed (${response.status}). Check the entered settings.`,
      );
    return response.json();
  }
  async function run(action: () => Promise<void>) {
    setBusy(true);
    setMessage("");
    try {
      await action();
    } catch (e) {
      setMessage(e instanceof Error ? e.message : "Request failed");
    } finally {
      setBusy(false);
    }
  }
  function change(next: Settings) {
    setSettings(next);
    setTested(false);
    setSaved(false);
  }
  return (
    <div className="shell">
      <aside>
        <div className="brand">◈ TRUST PORTAL</div>
        <p>Content provenance</p>
        <nav>
          <strong>Organization settings</strong>
          <span>Signing profiles</span>
          <span>Signing identities · upcoming</span>
          <span>Content signing · upcoming</span>
        </nav>
        <a href="/swagger-ui/index.html" target="_blank" rel="noreferrer">
          API documentation ↗
        </a>
      </aside>
      <main>
        <header>
          <span>ADMINISTRATION / FIRST-RUN SETUP</span>
          <h1>Your content. Your credentials.</h1>
          <p>
            Define the organization and claims your signing workflow will use.
          </p>
        </header>
        <div className="notice">
          Foundation release · Signing is unavailable until the key provider and
          worker are connected. Never enter private keys here.
        </div>
        {!state ? (
          <section>
            <h2>Connect as administrator</h2>
            <p>
              Use the bootstrap token generated by the local backend. It stays
              in memory for this session.
            </p>
            <label>
              Administrator token
              <input
                type="password"
                autoComplete="off"
                value={token}
                onChange={(e) => setToken(e.target.value)}
              />
            </label>
            <button
              disabled={busy || !token}
              onClick={() =>
                run(async () => {
                  const s = await request("");
                  setState(s);
                  setSettings(s.draft);
                })
              }
            >
              Connect
            </button>
          </section>
        ) : (
          settings && (
            <>
              <section>
                <div className="section-title">
                  <h2>Organization & signing profile</h2>
                  <span className="badge">Revision {state.revision}</span>
                </div>
                <label>
                  Organization name
                  <input
                    maxLength={120}
                    value={settings.organizationName}
                    onChange={(e) =>
                      change({ ...settings, organizationName: e.target.value })
                    }
                  />
                </label>
                <label>
                  Profile name
                  <input
                    maxLength={120}
                    value={settings.profileName}
                    onChange={(e) =>
                      change({ ...settings, profileName: e.target.value })
                    }
                  />
                </label>
                <fieldset>
                  <legend>Planned content formats</legend>
                  {["image/jpeg", "image/png"].map((format) => (
                    <label className="check" key={format}>
                      <input
                        type="checkbox"
                        checked={settings.formats.includes(format)}
                        onChange={(e) =>
                          change({
                            ...settings,
                            formats: e.target.checked
                              ? [...settings.formats, format]
                              : settings.formats.filter((f) => f !== format),
                          })
                        }
                      />
                      {format === "image/jpeg" ? "JPEG images" : "PNG images"}
                    </label>
                  ))}
                </fieldset>
                <label>
                  Maximum upload size (MB)
                  <input
                    type="number"
                    min={1}
                    max={100}
                    value={settings.maxUploadMb}
                    onChange={(e) =>
                      change({
                        ...settings,
                        maxUploadMb: Number(e.target.value),
                      })
                    }
                  />
                </label>
                <label className="check">
                  <input
                    type="checkbox"
                    checked={settings.requireAiDisclosure}
                    onChange={(e) =>
                      change({
                        ...settings,
                        requireAiDisclosure: e.target.checked,
                      })
                    }
                  />
                  Require an AI disclosure declaration
                </label>
                <div className="actions">
                  <button
                    disabled={busy}
                    onClick={() =>
                      run(async () => {
                        const s = await request("/draft", "PUT", {
                          settings,
                          revision: state.revision,
                        });
                        setState(s);
                        setSaved(true);
                        setTested(false);
                        setMessage("Draft saved.");
                      })
                    }
                  >
                    Save draft
                  </button>
                  <button
                    className="secondary"
                    disabled={busy || !saved}
                    onClick={() =>
                      run(async () => {
                        const result = await request(
                          "/draft/test",
                          "POST",
                          settings,
                        );
                        setTested(result.valid);
                        setMessage(result.message);
                      })
                    }
                  >
                    Validate profile
                  </button>
                  <button
                    className="secondary"
                    disabled={busy || !tested || !saved}
                    onClick={() =>
                      run(async () => {
                        const s = await request("/draft/activate", "POST", {
                          revision: state.revision,
                        });
                        setState(s);
                        setMessage(
                          "Profile activated. Signing remains unavailable.",
                        );
                      })
                    }
                  >
                    Activate profile
                  </button>
                </div>
              </section>
              <section>
                <h2>Inspect content credentials</h2>
                <p>
                  Upload a JPEG or PNG with an embedded C2PA manifest.
                  Cryptographic integrity and signer trust are separate results;
                  inspect the reported validation statuses.
                </p>
                <label>
                  Content file
                  <input
                    type="file"
                    accept="image/jpeg,image/png"
                    onChange={(e) => {
                      setFile(e.target.files?.[0] ?? null);
                      setReport(null);
                    }}
                  />
                </label>
                <button
                  disabled={busy || !file || !state.active}
                  onClick={() =>
                    run(async () => {
                      if (!file) return;
                      const body = new FormData();
                      body.append("file", file);
                      const response = await fetch("/api/v1/verification", {
                        method: "POST",
                        headers: { "X-Admin-Token": token },
                        body,
                      });
                      if (!response.ok)
                        throw new Error(
                          response.status === 422
                            ? "No readable C2PA manifest, or malformed content."
                            : `Inspection failed (${response.status}).`,
                        );
                      setReport(await response.json());
                      setMessage(
                        "Inspection complete. Review validation details below.",
                      );
                    })
                  }
                >
                  Inspect manifest
                </button>
                {report !== null && (
                  <pre>{JSON.stringify(report, null, 2)}</pre>
                )}
              </section>
              <section>
                <h2>Active configuration</h2>
                {state.active ? (
                  <p>
                    <strong>{state.active.organizationName}</strong> ·{" "}
                    {state.active.profileName}
                    <br />
                    {state.active.formats.join(", ")} · up to{" "}
                    {state.active.maxUploadMb} MB
                  </p>
                ) : (
                  <p>
                    No active profile. Save, validate, and activate your first
                    profile.
                  </p>
                )}
                <button
                  className="secondary"
                  onClick={() => {
                    setState(null);
                    setSettings(null);
                    setToken("");
                    setReport(null);
                    setFile(null);
                    setMessage("");
                    setTested(false);
                    setSaved(true);
                  }}
                >
                  Disconnect
                </button>
              </section>
            </>
          )
        )}
        <p role="status" aria-live="polite">
          {busy ? "Working…" : message}
        </p>
      </main>
    </div>
  );
}
createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
